# Generated by Django 5.2.6 on 2025-09-15 15:57

import core.models
import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Lowercase letters, numbers and hyphens only.",
                        max_length=220,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug must be lowercase letters/numbers with hyphens only (no spaces).",
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Internal stock keeping unit (unique).",
                        max_length=64,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("BDT", "Bangladeshi Taka"),
                            ("INR", "Indian Rupee"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="JPEG/PNG/WEBP only.",
                        null=True,
                        upload_to=core.models.product_image_upload_to,
                        validators=[core.models.validate_image_mime],
                    ),
                ),
                ("short_description", models.CharField(blank=True, max_length=250)),
                ("description", models.TextField(blank=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="idx_product_slug"),
                    models.Index(
                        fields=["is_active", "stock"], name="idx_product_active_stock"
                    ),
                    models.Index(fields=["created_at"], name="idx_product_created"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)),
                        name="chk_product_price_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stock__gte", 0)),
                        name="chk_product_stock_nonneg",
                    ),
                ],
            },
        ),
    ]
