# Generated by Django 5.2.6 on 2025-09-16 19:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_product_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("signup", "Sign Up"), ("login", "Login")],
                        default="signup",
                        max_length=16,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("attempts_left", models.PositiveSmallIntegerField(default=5)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "created_at"],
                        name="core_emailv_email_c7a9c0_idx",
                    )
                ],
            },
        ),
    ]
