# Generated by Django 5.2.6 on 2025-09-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_emailverificationcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerificationCode",
        ),
    ]
