# Generated by Django 5.2.6 on 2025-09-29 10:19

import core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_order_orderitem_payment_paymentevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug (auto-generated if empty)",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True, help_text="Short summary (optional)", max_length=300
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Write your post (HTML allowed for admins)."
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="Optional cover image",
                        null=True,
                        upload_to=core.models.blog_image_upload_to,
                        validators=[core.models.validate_image_mime],
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated tags (optional)",
                        max_length=200,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="idx_blog_slug"),
                    models.Index(
                        fields=["is_published", "published_at"], name="idx_blog_pub"
                    ),
                    models.Index(fields=["created_at"], name="idx_blog_created"),
                ],
            },
        ),
    ]
