# Generated by Django 5.2.6 on 2025-10-07 09:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_file",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.order_file_upload_to
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="processing_status",
            field=models.CharField(
                blank=True,
                choices=[("running", "Running"), ("complete", "Complete")],
                default="running",
                max_length=20,
            ),
        ),
    ]
