# Generated by Django 5.2.6 on 2025-10-07 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_order_delivery_file_order_processing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_order_no",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("twocheckout", "2Checkout"),
                    ("sslcommerz", "SSLCommerz"),
                    ("stripe", "Stripe"),
                    ("coin", "Coin/Manual"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["processing_status"], name="idx_order_processing_status"
            ),
        ),
    ]
