# Generated by Django 5.2.6 on 2025-10-08 11:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_orderitem_delivery_file_orderitem_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="user_file",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.item_file_upload_to
            ),
        ),
    ]
